DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE GROUPLIST CASCADE CONSTRAINTS;
DROP TABLE GRMEM CASCADE CONSTRAINTS;
DROP TABLE LOG CASCADE CONSTRAINTS;
DROP TABLE CUPBOB CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE REPLY CASCADE CONSTRAINTS;

DROP sequence GROUPLIST_SEQ;
DROP sequence GRMEM_SEQ;
DROP sequence CUPBOB_SEQ;
DROP sequence LOG_SEQ;
DROP sequence BOARD_SEQ;
DROP sequence REPLY_SEQ;


