--회원 : 아이디, 멤버이름, 비밀번호, 핸드폰, 로그인날짜, 가입날짜

INSERT INTO MEMBER values('ID2', '이름', '패스워드', '01012345678', NULL, SYSDATE);
INSERT INTO MEMBER values('ID3', '김채연', '123123', '0103333333', NULL, SYSDATE);
INSERT INTO MEMBER values('ID4', '김형규', '1234', '0104444444', NULL, SYSDATE);
INSERT INTO MEMBER values('ID5', '곽지훈', '1234', '01055555555', NULL, SYSDATE);

INSERT INTO MEMBER values('ID6', '김나리', '1234', '01012121212', NULL, SYSDATE);
INSERT INTO MEMBER values('ID7', '김시욱', '1234', '01012312322', NULL, SYSDATE);
INSERT INTO MEMBER values('ID8', '김인희', '1234', '0109887222', NULL, SYSDATE);
INSERT INTO MEMBER values('ID9', '김재현', '1234', '01099999999', NULL, SYSDATE);
INSERT INTO MEMBER values('ID10', '박동진', '1234', '01099998888', NULL, SYSDATE);
INSERT INTO MEMBER values('ID11', '박상우', '1234', '01088887777', NULL, SYSDATE);
INSERT INTO MEMBER values('ID12', '변정우', '1234', '01088884444', NULL, SYSDATE);
INSERT INTO MEMBER values('ID13', '이도연', '1234', '01088883212', NULL, SYSDATE);
INSERT INTO MEMBER values('ID14', '이재하', '1234', '01077776666', NULL, SYSDATE);
INSERT INTO MEMBER values('ID15', '이호균', '1234', '01012382323', NULL, SYSDATE);
INSERT INTO MEMBER values('ID16', '장성훈', '1234', '01055556666', NULL, SYSDATE);
INSERT INTO MEMBER values('ID17', '정선우', '1234', '01098765444', NULL, SYSDATE);
INSERT INTO MEMBER values('ID18', '정현서', '1234', '01098362321', NULL, SYSDATE);

--그룹 : 그룹고유번호, 그룹이름, 생성날짜
INSERT INTO GROUPLIST VALUES(GROUPLIST_SEQ.NEXTVAL, '채연아침밥조', SYSDATE);
INSERT INTO GROUPLIST VALUES(GROUPLIST_SEQ.NEXTVAL, '채연아점밥조', SYSDATE);
INSERT INTO GROUPLIST VALUES(GROUPLIST_SEQ.NEXTVAL, '채연점심밥조', SYSDATE);
INSERT INTO GROUPLIST VALUES(GROUPLIST_SEQ.NEXTVAL, '채연저녁밥조', SYSDATE);
INSERT INTO GROUPLIST VALUES(GROUPLIST_SEQ.NEXTVAL, '채연야식밥조', SYSDATE);

--그룹멤버 : 소속고유번호, 그룹고유번호, 아이디, 직책, 그룹가입일
-- 직책 M : 그룹장 N : 일반회원  
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 2, 'ID3', 'M', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 2, 'ID6', 'n', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 3, 'ID9', 'm', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 3, 'ID12', 'n', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 3, 'ID15', 'n', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 4, 'ID17', 'm', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 4, 'ID18', 'n', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 5, 'ID4', 'M', SYSDATE);
INSERT INTO GRMEM VALUES(GRMEM_SEQ.NEXTVAL, 5, 'ID11', 'n', SYSDATE);



--컵밥 소유 : 소유고유번호, 컵밥이름, 소속고유번호, 컵밥상태, 컵밥등록일, 컵밥소멸일
--컵밥상태  1 : 보유 , 2 : 상실

INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥', 2, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '강된장밥', 2, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 3, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥',4, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '강된장밥', 6, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 5, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥', 5, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 3, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '강된장밥', 4, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '강된장밥', 7, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥', 6, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 6, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥', 10, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '강된장밥', 3, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 7, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '오징어덮밥', 4, 1, SYSDATE,NULL);
INSERT INTO CUPBOB VALUES(CUPBOB_SEQ.NEXTVAL, '물개덮밥', 7, 1, SYSDATE,NULL);

--컵밥이동로그 : 로그고유번호, 로그구분번호, 컵밥발송, 컵밥수신, 이동일
INSERT INTO LOG();


--게시판 : 게시판고유번호, 말머리, 제목, 아이디, 내용, 소유고유번호, 완료여부, 비밀번호, 작성일
--완료여부 1 : 보유 2 : 상실 ???????? 완료여부잘모르겠다;
--말머리 T : 교환,  S : 판매, E : 기타
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID2', '내용', 2, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'S', '제목 판', 'ID4', '내용', 3, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID6', '내용', 4, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID8', '내용', 5, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'S', '제목 판', 'ID11', '내용', 6, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'S', '제목 판', 'ID13', '내용', 7, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID15', '내용', 8, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'S', '제목 판', 'ID7', '내용', 9, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID9', '내용', 12, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'S', '제목 판', 'ID5', '내용', 11, 1, 1234, SYSDATE);
INSERT INTO BOARD VALUES(BOARD_SEQ.NEXTVAL, 'T', '제목 교', 'ID17', '내용', 13, 1, 1234, SYSDATE);


--댓글 : 댓글고유번호, 아이디, 댓글내용, 선택유무, 댓글작성일, 게시판고유번호
--선택여부 1 : 선택 2 : 선택전
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL, 'ID2', '댓글', 0, SYSDATE, 4);
INSERT INTO REPLY VALUES(REPLY_SEQ.NEXTVAL, 'ID4', '댓글', 0, SYSDATE, 7);



COMMIT;